development:
  adapter: postgresql
  database: hooyu_development
  host: localhost
  min_messages: WARNING

test:
  adapter: postgresql
  database: hooyu_test
  host: localhost
  min_messages: WARNING
